name: ci
on:
  push:
    branches:
      - '**'
env:
  node: '22.11.0'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node }}
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - run: npm install
        if: steps.npm-cache.outputs.cache-hit != 'true'
      - run: npm run test
